/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planta;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static planta.PlantaFunciones.getNombresCalendarios;


/**
 *
 * @author XPC
 */
public class SimuladorMarcas extends javax.swing.JFrame {

    /**
     * Creates new form Marcas
     */
    private String[] opcionesConsulta;
    public SimuladorMarcas() {
        initComponents();
        actualizarCombosBox();
    }

    
    private void actualizarCombosBox(){
        try {
            jCBoxCalendarios.removeAllItems();
            opcionesConsulta = getNombresCalendarios();
            String[] opciones = opcionesConsulta[1].split(",");
            for (int i = 0; i < opciones.length; i++) {
                jCBoxCalendarios.addItem(opciones[i]);
                
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LblMarcas = new javax.swing.JLabel();
        TxtFieldFechaI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtnPrueba = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TxtFieldFechaF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCBoxCalendarios = new javax.swing.JComboBox<>();
        RBTodos = new javax.swing.JRadioButton();
        BtnFinal = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LblMarcas.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        LblMarcas.setForeground(new java.awt.Color(0, 0, 0));
        LblMarcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMarcas.setText("Generador de Marcas");

        TxtFieldFechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldFechaIActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha Inicial:");

        BtnPrueba.setBackground(new java.awt.Color(0, 0, 0));
        BtnPrueba.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrueba.setText("Prueba");
        BtnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPruebaActionPerformed(evt);
            }
        });

        BtnVolver.setBackground(new java.awt.Color(0, 0, 0));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha Final:");

        TxtFieldFechaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldFechaFActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCBoxCalendarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RBTodos.setForeground(new java.awt.Color(0, 0, 0));
        RBTodos.setText("Todos");

        BtnFinal.setBackground(new java.awt.Color(0, 0, 0));
        BtnFinal.setForeground(new java.awt.Color(255, 255, 255));
        BtnFinal.setText("Final");
        BtnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(BtnPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(BtnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnVolver)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblMarcas)
                .addGap(206, 206, 206))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(TxtFieldFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFieldFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(jCBoxCalendarios, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(RBTodos)
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jCBoxCalendarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBTodos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtFieldFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnVolver)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipal MPrincipal = new MenuPrincipal();
        MPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPruebaActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        String strFechaI = TxtFieldFechaI.getText();
        Pattern pattern = Pattern.compile("^((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$");
        Matcher mat = pattern.matcher(strFechaI);
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String strFechaF = TxtFieldFechaF.getText();
        if(!TxtFieldFechaF.getText().equals("")){
            mat = pattern.matcher(strFechaF);
            if(!mat.matches()){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
          if(PlantaFunciones.FechaCSentido(strFechaI, strFechaF) == false){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA DE INGRESO DEBE SER ANTERIOR A LA FECHA DE SALIDA", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        int Calendario = -1;
        if(!RBTodos.isSelected()){
            Calendario = Integer.parseInt(opcionesConsulta[0].split(",")[jCBoxCalendarios.getSelectedIndex()]);
        }
        int Contador = 0;
        String Final = "Empleado" + "\t\t" + "Entrada" + "\t\t" + "Salida" + "\t\t\n";
        int IdEmpleado;
        int IdCalendario;
        String Entrada = "";
        String Salida = "";
        ArrayList <String[]> Comprobador = new ArrayList();
        String Fecha;
        while(Contador<=15){
            if(!strFechaF.equals("")){
                Fecha = PlantaFunciones.generarFechas(Integer.parseInt(strFechaI.substring(0,4)), 
                    Integer.parseInt(strFechaI.substring(5,7)), Integer.parseInt(strFechaI.substring(8)),
                    Integer.parseInt(strFechaF.substring(0,4)), Integer.parseInt(strFechaF.substring(5,7)),
                    Integer.parseInt(strFechaF.substring(8)), strFechaF.substring(0,4));
            }
            else{
                Fecha = strFechaI;
            }
            IdEmpleado = PlantaFunciones.verificarMarca(Fecha, Calendario);
            if(IdEmpleado != -1){
                if(PlantaFunciones.VerificarCComprobador(Comprobador, IdEmpleado + "", Fecha) == true){
                    IdCalendario = PlantaFunciones.ObtenerIdCalendario(IdEmpleado);
                    Entrada = PlantaFunciones.ObtenerEntradaM(Fecha, IdCalendario);
                    Salida = PlantaFunciones.ObtenerSalidaM(Fecha, IdCalendario);
                    Final += IdEmpleado + "\t\t" + Entrada + "\t\t" + Salida + "\t\t\n";
                    Comprobador.add(new String[]{IdEmpleado + "", Fecha});
                }
            }
            
            Contador ++;
        }
        jTextArea1.setText(Final);
        
        
    }//GEN-LAST:event_BtnPruebaActionPerformed

    private void TxtFieldFechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldFechaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldFechaIActionPerformed

    private void TxtFieldFechaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldFechaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldFechaFActionPerformed

    private void BtnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        String strFechaI = TxtFieldFechaI.getText();
        Pattern pattern = Pattern.compile("^((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$");
        Matcher mat = pattern.matcher(strFechaI);
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String strFechaF = TxtFieldFechaF.getText();
        if(!TxtFieldFechaF.getText().equals("")){
            mat = pattern.matcher(strFechaF);
            if(!mat.matches()){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
          if(PlantaFunciones.FechaCSentido(strFechaI, strFechaF) == false){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA DE INGRESO DEBE SER ANTERIOR A LA FECHA DE SALIDA", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        int Calendario = -1;
        if(!RBTodos.isSelected()){
            Calendario = Integer.parseInt(opcionesConsulta[0].split(",")[jCBoxCalendarios.getSelectedIndex()]);
        }
        int Contador = 0;
        String Final = "Empleado" + "\t\t" + "Entrada" + "\t\t" + "Salida" + "\t\t\n";
        int IdEmpleado;
        int IdCalendario;
        String Entrada = "";
        String Salida = "";
        String Fecha;
        while(Contador<=15){
            if(!strFechaF.equals("")){
                Fecha = PlantaFunciones.generarFechas(Integer.parseInt(strFechaI.substring(0,4)), 
                    Integer.parseInt(strFechaI.substring(5,7)), Integer.parseInt(strFechaI.substring(8)),
                    Integer.parseInt(strFechaF.substring(0,4)), Integer.parseInt(strFechaF.substring(5,7)),
                    Integer.parseInt(strFechaF.substring(8)), strFechaF.substring(0,4));
            }
            else{
                Fecha = strFechaI;
            }
            IdEmpleado = PlantaFunciones.verificarMarca(Fecha, Calendario);
            if(IdEmpleado != -1){
                IdCalendario = PlantaFunciones.ObtenerIdCalendario(IdEmpleado);
                Entrada = PlantaFunciones.ObtenerEntradaM(Fecha, IdCalendario);
                Salida = PlantaFunciones.ObtenerSalidaM(Fecha, IdCalendario);
                PlantaFunciones.InsertarMarcasFinal(IdEmpleado, Entrada, Salida);
                Final += IdEmpleado + "\t\t" + Entrada + "\t\t" + Salida + "\t\t\n";
                //Llamar Funcion con SP para insertar las marcas en la BD
            }
            Contador ++;
        }
        jTextArea1.setText(Final);
    }//GEN-LAST:event_BtnFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFinal;
    private javax.swing.JButton BtnPrueba;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblMarcas;
    private javax.swing.JRadioButton RBTodos;
    private javax.swing.JTextField TxtFieldFechaF;
    private javax.swing.JTextField TxtFieldFechaI;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> jCBoxCalendarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
