/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planta;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author XPC
 */
public class CalculoPlanilla extends javax.swing.JFrame {

    private String[] opcionesConsultaCalendario;
    private String[] opcionesConsultaFechasDPago;
    
    private int idCalendario;
    private String fechaInicialDPagoSeleccionada;
    private String fechaFinalDPagoSeleccionada;
    
    private String[] lineasSalida = null;
    /**
     * Creates new form Marcas
     */
    public CalculoPlanilla() {
        initComponents();
        
        actualizarCombosBoxCalendario();
        
        comboBoxCalendario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarComboBoxFechasDPago();
            }
                
        });

        
        actualizarComboBoxFechasDPago();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LblMarcas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaConsulta = new javax.swing.JTextArea();
        BTNVolver = new javax.swing.JButton();
        comboBoxCalendario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxFechasDPago = new javax.swing.JComboBox<>();
        BTNConsultarPlanilla = new javax.swing.JButton();
        BTNAprobarPlanilla = new javax.swing.JButton();
        BTNRechazarPlanilla = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LblMarcas.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        LblMarcas.setForeground(new java.awt.Color(0, 0, 0));
        LblMarcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMarcas.setText("Cálculo de Planilla");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seleccione el calendario a pagar:");

        txtAreaConsulta.setColumns(20);
        txtAreaConsulta.setRows(5);
        jScrollPane1.setViewportView(txtAreaConsulta);

        BTNVolver.setBackground(new java.awt.Color(0, 0, 0));
        BTNVolver.setForeground(new java.awt.Color(255, 255, 255));
        BTNVolver.setText("Volver");
        BTNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolverActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seleccione la fecha a pagar:");

        BTNConsultarPlanilla.setBackground(new java.awt.Color(0, 0, 0));
        BTNConsultarPlanilla.setForeground(new java.awt.Color(255, 255, 255));
        BTNConsultarPlanilla.setText("CONSULTAR PLANILLA");
        BTNConsultarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConsultarPlanillaActionPerformed(evt);
            }
        });

        BTNAprobarPlanilla.setBackground(new java.awt.Color(0, 0, 0));
        BTNAprobarPlanilla.setForeground(new java.awt.Color(255, 255, 255));
        BTNAprobarPlanilla.setText("APROBAR PLANILLA");
        BTNAprobarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAprobarPlanillaActionPerformed(evt);
            }
        });

        BTNRechazarPlanilla.setBackground(new java.awt.Color(0, 0, 0));
        BTNRechazarPlanilla.setForeground(new java.awt.Color(255, 255, 255));
        BTNRechazarPlanilla.setText("RECHAZAR PLANILLA");
        BTNRechazarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRechazarPlanillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(LblMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxCalendario, 0, 109, Short.MAX_VALUE)
                                    .addComponent(comboBoxFechasDPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(BTNVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNConsultarPlanilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNAprobarPlanilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNRechazarPlanilla)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxFechasDPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConsultarPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAprobarPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNRechazarPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolverActionPerformed
        // TODO add your handling code here:
        if (idCalendario != -1) {
            JOptionPane.showMessageDialog(this, "Favor primero aceptar o rechazar la consulta de planilla rechazada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.setVisible(false);
        MenuPrincipal MPrincipal = new MenuPrincipal();
        MPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNVolverActionPerformed

    private void BTNConsultarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConsultarPlanillaActionPerformed
        // TODO add your handling code here:
        int idSeleccionado = Integer.parseInt(opcionesConsultaCalendario[0].split(",")[comboBoxCalendario.getSelectedIndex()]);
        String fechaInicial;
        try {
            fechaInicial = opcionesConsultaFechasDPago[1].split(",")[comboBoxFechasDPago.getSelectedIndex() - 1];
        } catch (IndexOutOfBoundsException e) {
            fechaInicial = opcionesConsultaFechasDPago[1].split(",")[opcionesConsultaFechasDPago[1].split(",").length - 1];
            fechaInicial = "2022" + fechaInicial.substring(4);
        }
        String fechaFinal = (String) comboBoxFechasDPago.getSelectedItem();
        if (!PlantaFunciones.verificarExtrasPendientesPf(idSeleccionado, fechaInicial, fechaFinal)) {
            JOptionPane.showMessageDialog(this, "Para acceder a esta función primero debe aproba o rechazar las revisiones de horas extra pendientes", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        idCalendario = idSeleccionado;
        fechaInicialDPagoSeleccionada = fechaInicial;
        fechaFinalDPagoSeleccionada = fechaFinal;
        
        // consultar planilla
        lineasSalida = PlantaFunciones.calcularPlanilla(idCalendario, fechaInicial, fechaFinal);
        
        String[] elementosLinea;
        
        String resultadoTextArea = "IdEmpleado \t Fecha Pago \t Salario Bruto \t Salario Neto \t Planta \t Tipo Pago \n";
        for (int i = 1; i < lineasSalida.length; i++) {
            elementosLinea = lineasSalida[i].split("\t");
            if (PlantaFunciones.verificarIdEmpleadoEnPlanilla(Integer.parseInt(elementosLinea[0]), fechaFinalDPagoSeleccionada)) {
                int idEmpleadoIns = Integer.parseInt(elementosLinea[0]);
                String fechaDPago = fechaFinalDPagoSeleccionada;
                float montoPagadoBruto = Float.parseFloat(elementosLinea[1]);
                float montoPagadoNeto = Float.parseFloat(elementosLinea[2]);
                
                // cambiar por app
                String planta = "Guayabo";
                int tipoDPago = PlantaFunciones.consultarTipoDPagoNUMPorCalendario(idCalendario);
                
                resultadoTextArea += idEmpleadoIns + "\t" + fechaDPago + "\t" + montoPagadoBruto + "\t" + montoPagadoNeto + "\t" + planta + "\t" + tipoDPago + "\n";
                PlantaFunciones.InsertarPlanilla(idEmpleadoIns, fechaDPago, montoPagadoBruto, montoPagadoNeto, planta, tipoDPago);
            }
        }
        // INSERTAR PLANILLA
        
        // muestra en text area
        txtAreaConsulta.setText(resultadoTextArea);
    }//GEN-LAST:event_BTNConsultarPlanillaActionPerformed

    private void BTNAprobarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAprobarPlanillaActionPerformed
        // TODO add your handling code here:
        if (idCalendario == -1 || lineasSalida == null) {
            JOptionPane.showMessageDialog(this, "Favor consultar planilla", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int tipoDPago = PlantaFunciones.consultarTipoDPagoNUMPorCalendario(idCalendario);
        PlantaFunciones.generarCSV(fechaFinalDPagoSeleccionada, tipoDPago);
        
        idCalendario = -1;
        fechaInicialDPagoSeleccionada = "";
        fechaFinalDPagoSeleccionada = "";
        txtAreaConsulta.setText("");
        JOptionPane.showMessageDialog(this, "Proceso realizado de manera exitosa", "!!", JOptionPane.INFORMATION_MESSAGE);
        return;
    }//GEN-LAST:event_BTNAprobarPlanillaActionPerformed

    private void BTNRechazarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRechazarPlanillaActionPerformed
        // TODO add your handling code here:
        try {
            if (idCalendario == -1 || lineasSalida == null) {
                JOptionPane.showMessageDialog(this, "Favor consultar planilla", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String[] elementosLinea;
            for (int i = 1; i < lineasSalida.length; i++) {
                elementosLinea = lineasSalida[i].split("\t");
                int idEmpleadoEli = Integer.parseInt(elementosLinea[0]);
                String fechaDPago = fechaFinalDPagoSeleccionada;
                PlantaFunciones.EliminarDPlanilla(idEmpleadoEli, fechaDPago);
            }
            
            idCalendario = -1;
            fechaInicialDPagoSeleccionada = "";
            fechaFinalDPagoSeleccionada = "";
            txtAreaConsulta.setText("");
            JOptionPane.showMessageDialog(this, "Proceso realizado de manera exitosa", "!!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BTNRechazarPlanillaActionPerformed

    private void actualizarCombosBoxCalendario(){
        comboBoxCalendario.removeAllItems();
        try {
            opcionesConsultaCalendario = PlantaFunciones.getNombresCalendarios();
            String[] opciones = opcionesConsultaCalendario[1].split(",");
            for (int i = 0; i < opciones.length; i++) {

                comboBoxCalendario.addItem(opciones[i]);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void actualizarComboBoxFechasDPago(){
        comboBoxFechasDPago.removeAllItems();
        try {
            int idSeleccionado = Integer.parseInt(opcionesConsultaCalendario[0].split(",")[comboBoxCalendario.getSelectedIndex()]);
            opcionesConsultaFechasDPago = PlantaFunciones.TraerDiasDPago(idSeleccionado);
            String[] opciones = opcionesConsultaFechasDPago[1].split(",");
            for (int i = 0; i < opciones.length; i++) {

                comboBoxFechasDPago.addItem(opciones[i]);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoPlanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAprobarPlanilla;
    private javax.swing.JButton BTNConsultarPlanilla;
    private javax.swing.JButton BTNRechazarPlanilla;
    private javax.swing.JButton BTNVolver;
    private javax.swing.JLabel LblMarcas;
    private javax.swing.JComboBox<String> comboBoxCalendario;
    private javax.swing.JComboBox<String> comboBoxFechasDPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaConsulta;
    // End of variables declaration//GEN-END:variables
}
