/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planta;

import java.util.Date;
import javax.swing.JOptionPane;
import java.util.regex.*;

/**
 *
 * @author prend
 */
public class EmpleadoCRUD extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public EmpleadoCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelConsulta = new javax.swing.JPanel();
        botonConsulta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        panelTextArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        panelEditar = new javax.swing.JPanel();
        botonEditar = new javax.swing.JButton();
        panelEliminar = new javax.swing.JPanel();
        botonEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        agregarFDNombre = new javax.swing.JTextField();
        agregarFDApellidos = new javax.swing.JTextField();
        agregarFDFechaIngreso = new javax.swing.JTextField();
        agregarFDFechaSalida = new javax.swing.JTextField();
        agregarFDIdDepartamento = new javax.swing.JTextField();
        agregarFDIdSupervisor = new javax.swing.JTextField();
        agregarFDIdTipo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        editarFDIdEmpleado = new javax.swing.JTextField();
        editarFDNombre = new javax.swing.JTextField();
        editarFDApellidos = new javax.swing.JTextField();
        editarFDFechaIngreso = new javax.swing.JTextField();
        editarFDFechaSalida = new javax.swing.JTextField();
        editarFDIdDepartamento = new javax.swing.JTextField();
        editarFDIdSupervisor = new javax.swing.JTextField();
        editarFDIdTipo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        eliminarFDIdEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BTNConsultarDepartamentos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        panelConsulta.setBackground(new java.awt.Color(255, 255, 255));

        botonConsulta.setBackground(new java.awt.Color(0, 0, 0));
        botonConsulta.setForeground(new java.awt.Color(255, 255, 255));
        botonConsulta.setText("CONSULTAR");
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultaLayout = new javax.swing.GroupLayout(panelConsulta);
        panelConsulta.setLayout(panelConsultaLayout);
        panelConsultaLayout.setHorizontalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultaLayout.setVerticalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        botonAgregar.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregar.setText("AGREGAR");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTextArea.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout panelTextAreaLayout = new javax.swing.GroupLayout(panelTextArea);
        panelTextArea.setLayout(panelTextAreaLayout);
        panelTextAreaLayout.setHorizontalGroup(
            panelTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelTextAreaLayout.setVerticalGroup(
            panelTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTextAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelEditar.setBackground(new java.awt.Color(255, 255, 255));

        botonEditar.setBackground(new java.awt.Color(0, 0, 0));
        botonEditar.setForeground(new java.awt.Color(255, 255, 255));
        botonEditar.setText("EDITAR");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelEliminar.setBackground(new java.awt.Color(255, 255, 255));

        botonEliminar.setBackground(new java.awt.Color(0, 0, 0));
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("ELIMINAR");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellidos");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha Ingreso");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha Salida");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("IdDepartamento");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("IdSupervisor");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("IdTipoEmpleado");

        agregarFDNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDNombreActionPerformed(evt);
            }
        });

        agregarFDApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDApellidosActionPerformed(evt);
            }
        });

        agregarFDFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDFechaIngresoActionPerformed(evt);
            }
        });

        agregarFDFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDFechaSalidaActionPerformed(evt);
            }
        });

        agregarFDIdDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDIdDepartamentoActionPerformed(evt);
            }
        });

        agregarFDIdSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDIdSupervisorActionPerformed(evt);
            }
        });

        agregarFDIdTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDIdTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarFDNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarFDApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarFDFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarFDFechaSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarFDIdDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarFDIdSupervisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarFDIdTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(agregarFDNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDIdDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDIdSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(agregarFDIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("IdEmpleado");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Nombre");

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Apellidos");

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Fecha Ingreso");

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Fecha Salida");

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("IdDepartamento");

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("IdSupervisor");

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("IdTipoEmpleado");

        editarFDIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDIdEmpleadoActionPerformed(evt);
            }
        });

        editarFDNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDNombreActionPerformed(evt);
            }
        });

        editarFDApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDApellidosActionPerformed(evt);
            }
        });

        editarFDFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDFechaIngresoActionPerformed(evt);
            }
        });

        editarFDFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDFechaSalidaActionPerformed(evt);
            }
        });

        editarFDIdDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDIdDepartamentoActionPerformed(evt);
            }
        });

        editarFDIdSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDIdSupervisorActionPerformed(evt);
            }
        });

        editarFDIdTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDIdTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarFDIdEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarFDNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarFDApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarFDFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarFDFechaSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarFDIdDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarFDIdSupervisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFDIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(editarFDIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFDNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFDApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFDFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(editarFDFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(editarFDIdDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(editarFDIdSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(editarFDIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("IdEmpleado");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("<html>Cuidado, esta función eliminará todas las marcas del empleado(en caso de tenerlas)<html>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(eliminarFDIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarFDIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(35, 35, 35)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTNConsultarDepartamentos.setBackground(new java.awt.Color(0, 0, 0));
        BTNConsultarDepartamentos.setForeground(new java.awt.Color(255, 255, 255));
        BTNConsultarDepartamentos.setText("<html>Consultar Departamentos<html>");
        BTNConsultarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConsultarDepartamentosActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<html>Consultar Tipos de Empleado<html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNConsultarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(panelTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(BTNConsultarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        String str = PlantaFunciones.MostrarEmpleados();
        textArea.setText(str);
    }//GEN-LAST:event_botonConsultaActionPerformed

    private void agregarFDNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDNombreActionPerformed

    private void agregarFDApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDApellidosActionPerformed

    private void agregarFDFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDFechaIngresoActionPerformed

    private void agregarFDFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDFechaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDFechaSalidaActionPerformed

    private void agregarFDIdDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDIdDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDIdDepartamentoActionPerformed

    private void editarFDIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDIdEmpleadoActionPerformed

    private void editarFDNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDNombreActionPerformed

    private void editarFDApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDApellidosActionPerformed

    private void editarFDFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDFechaIngresoActionPerformed

    private void editarFDFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDFechaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDFechaSalidaActionPerformed

    private void editarFDIdDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDIdDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDIdDepartamentoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        String StrIdEmpleado = editarFDIdEmpleado.getText();
        if(PlantaFunciones.isNumeric(StrIdEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdEmpleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdEmpleado = Integer.parseInt(StrIdEmpleado);
        if(PlantaFunciones.VerificarIdEmpleadoEmpleados(IdEmpleado) == false){
           JOptionPane.showMessageDialog(this, 
                    "NO HAY UN EMPLEADO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        if(editarFDNombre.getText().length() == 0){
           JOptionPane.showMessageDialog(this, 
                    "Debe ingresar al menos un nombre", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String Nombre = editarFDNombre.getText();
        if(editarFDApellidos.getText().length() == 0){
           JOptionPane.showMessageDialog(this, 
                    "Debe ingresar los apellidos del empleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String Apellidos = editarFDApellidos.getText();
        
        
        String strFechaI = editarFDFechaIngreso.getText();
        Pattern pattern = Pattern.compile("^((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$");
        Matcher mat = pattern.matcher(strFechaI);
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String strFechaS = editarFDFechaSalida.getText();
        if(strFechaS.length() != 0){
            mat = pattern.matcher(strFechaS);
            if(!mat.matches()){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(PlantaFunciones.FechaCSentido(strFechaI, strFechaS) == false){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA DE INGRESO DEBE SER ANTERIOR A LA FECHA DE SALIDA", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        
        String StrIdDepartamento = editarFDIdDepartamento.getText();
        if(PlantaFunciones.isNumeric(StrIdDepartamento) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdDepartamento", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdDepartamento = Integer.parseInt(StrIdDepartamento);
        if(PlantaFunciones.VerificarIdDepartamentoDPO(IdDepartamento) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN DEPARTAMENTO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String StrIdSupervisor = editarFDIdSupervisor.getText();
        if(PlantaFunciones.isNumeric(StrIdSupervisor) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdSupervisor", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdSupervisor = Integer.parseInt(StrIdSupervisor);
        if(PlantaFunciones.VerificarIdEmpleadoEmpleados(IdSupervisor) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN POSIBLE SUPERVISOR(EMPLEADO) CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String StrIdTipoEmpleado = editarFDIdTipo.getText();
        if(PlantaFunciones.isNumeric(StrIdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdTipoEmpleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdTipoEmpleado = Integer.parseInt(StrIdTipoEmpleado);
        if(PlantaFunciones.VerificarIdTipoEmpleadoTE(IdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN TIPO DE EMPLEADO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int SalarioBruto = PlantaFunciones.ObtenerSBruto(IdTipoEmpleado);
        int SalarioHora = PlantaFunciones.ObtenerSHora(IdTipoEmpleado);
        boolean Bandera = PlantaFunciones.EditarEmpleado(IdEmpleado, Nombre, Apellidos, strFechaI, strFechaS, SalarioBruto, 
                SalarioHora, IdDepartamento, IdSupervisor, IdTipoEmpleado);
        if(Bandera == true){
            JOptionPane.showMessageDialog(this, 
                    "EL PROCESO SE HA REALIZADO DE MANERA EXITOSA", 
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }else{
            JOptionPane.showMessageDialog(this, 
                    "NO SE HA REALIZADO EL PROCESO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        if(agregarFDNombre.getText().length() == 0){
           JOptionPane.showMessageDialog(this, 
                    "Debe ingresar al menos un nombre", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String Nombre = agregarFDNombre.getText();
        if(agregarFDApellidos.getText().length() == 0){
           JOptionPane.showMessageDialog(this, 
                    "Debe ingresar los apellidos del nuevo empleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String Apellidos = agregarFDApellidos.getText();
        
        String strFechaI = agregarFDFechaIngreso.getText();
        Pattern pattern = Pattern.compile("^((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$");
        Matcher mat = pattern.matcher(strFechaI);
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String strFechaS = agregarFDFechaSalida.getText();
        if(strFechaS.length() != 0){
            mat = pattern.matcher(strFechaS);
            if(!mat.matches()){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(PlantaFunciones.FechaCSentido(strFechaI, strFechaS) == false){
            JOptionPane.showMessageDialog(this, 
                    "LA FECHA DE INGRESO DEBE SER ANTERIOR A LA FECHA DE SALIDA", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        
        String StrIdDepartamento = agregarFDIdDepartamento.getText();
        if(PlantaFunciones.isNumeric(StrIdDepartamento) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdDepartamento", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdDepartamento = Integer.parseInt(StrIdDepartamento);
        if(PlantaFunciones.VerificarIdDepartamentoDPO(IdDepartamento) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN DEPARTAMENTO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String StrIdSupervisor = agregarFDIdSupervisor.getText();
        if(PlantaFunciones.isNumeric(StrIdSupervisor) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdSupervisor", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdSupervisor = Integer.parseInt(StrIdSupervisor);
        if(PlantaFunciones.VerificarIdEmpleadoEmpleados(IdSupervisor) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN POSIBLE SUPERVISOR(EMPLEADO) CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String StrIdTipoEmpleado = agregarFDIdTipo.getText();
        if(PlantaFunciones.isNumeric(StrIdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdTipoEmpleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdTipoEmpleado = Integer.parseInt(StrIdTipoEmpleado);
        if(PlantaFunciones.VerificarIdTipoEmpleadoTE(IdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN TIPO DE EMPLEADO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String NombrePlanta = "Guayabo";
        int SalarioBruto = PlantaFunciones.ObtenerSBruto(IdTipoEmpleado);
        int SalarioHora = PlantaFunciones.ObtenerSHora(IdTipoEmpleado);
        boolean Bandera = PlantaFunciones.InsertarEmpleado( Nombre, Apellidos, strFechaI, strFechaS, SalarioBruto, 
                SalarioHora, NombrePlanta, IdDepartamento, IdSupervisor, IdTipoEmpleado);
        if(Bandera == true){
            JOptionPane.showMessageDialog(this, 
                    "EL PROCESO SE HA REALIZADO DE MANERA EXITOSA", 
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }else{
            JOptionPane.showMessageDialog(this, 
                    "NO SE HA REALIZADO EL PROCESO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        String StrIdEmpleado = eliminarFDIdEmpleado.getText();
        if(PlantaFunciones.isNumeric(StrIdEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdEmpleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdEmpleado = Integer.parseInt(StrIdEmpleado);
        if(PlantaFunciones.VerificarIdEmpleadoEmpleados(IdEmpleado) == false){
           JOptionPane.showMessageDialog(this, 
                    "NO HAY UN EMPLEADO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        boolean Bandera1 = PlantaFunciones.EliminarMarcasDEmpleado(IdEmpleado);
        if(Bandera1 == true){
            boolean Bandera2 = PlantaFunciones.EliminarEmpleado(IdEmpleado);
            if(Bandera2 == true){
                JOptionPane.showMessageDialog(this, 
                    "EL PROCESO SE HA REALIZADO DE MANERA EXITOSA", 
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
            }else{
                JOptionPane.showMessageDialog(this, 
                    "NO SE HA REALIZADO EL PROCESO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void agregarFDIdSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDIdSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDIdSupervisorActionPerformed

    private void agregarFDIdTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDIdTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDIdTipoActionPerformed

    private void editarFDIdSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDIdSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDIdSupervisorActionPerformed

    private void editarFDIdTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDIdTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDIdTipoActionPerformed

    private void BTNConsultarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConsultarDepartamentosActionPerformed
        // TODO add your handling code here:
        String str = PlantaFunciones.MostrarInfDepartamentos();
        textArea.setText(str);
    }//GEN-LAST:event_BTNConsultarDepartamentosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String str = PlantaFunciones.MostrarInfTiposEmpledos();
        textArea.setText(str);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNConsultarDepartamentos;
    private javax.swing.JTextField agregarFDApellidos;
    private javax.swing.JTextField agregarFDFechaIngreso;
    private javax.swing.JTextField agregarFDFechaSalida;
    private javax.swing.JTextField agregarFDIdDepartamento;
    private javax.swing.JTextField agregarFDIdSupervisor;
    private javax.swing.JTextField agregarFDIdTipo;
    private javax.swing.JTextField agregarFDNombre;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField editarFDApellidos;
    private javax.swing.JTextField editarFDFechaIngreso;
    private javax.swing.JTextField editarFDFechaSalida;
    private javax.swing.JTextField editarFDIdDepartamento;
    private javax.swing.JTextField editarFDIdEmpleado;
    private javax.swing.JTextField editarFDIdSupervisor;
    private javax.swing.JTextField editarFDIdTipo;
    private javax.swing.JTextField editarFDNombre;
    private javax.swing.JTextField eliminarFDIdEmpleado;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTextArea;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
