/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planta;

/**
 *
 * @author XPC
 */
public class MenuCrud extends javax.swing.JFrame {

    /**
     * Creates new form MenuCrud
     */
    public MenuCrud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BTNCalendariosCRUD = new javax.swing.JButton();
        BTNDFeriados = new javax.swing.JButton();
        BTNDepartamentos = new javax.swing.JButton();
        BTNEmpleados = new javax.swing.JButton();
        BTNTipoEmpleado = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        BTNDiasTrabajados = new javax.swing.JButton();

        BTNVolver.setBackground(new java.awt.Color(0, 0, 0));
        BTNVolver.setForeground(new java.awt.Color(255, 255, 255));
        BTNVolver.setText("Volver");
        BTNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolverActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BTNCalendariosCRUD.setBackground(new java.awt.Color(0, 0, 0));
        BTNCalendariosCRUD.setForeground(new java.awt.Color(255, 255, 255));
        BTNCalendariosCRUD.setText("Calendarios");
        BTNCalendariosCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCalendariosCRUDActionPerformed(evt);
            }
        });

        BTNDFeriados.setBackground(new java.awt.Color(0, 0, 0));
        BTNDFeriados.setForeground(new java.awt.Color(255, 255, 255));
        BTNDFeriados.setText("Días Feriados");
        BTNDFeriados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDFeriadosActionPerformed(evt);
            }
        });

        BTNDepartamentos.setBackground(new java.awt.Color(0, 0, 0));
        BTNDepartamentos.setForeground(new java.awt.Color(255, 255, 255));
        BTNDepartamentos.setText("Departamentos");
        BTNDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDepartamentosActionPerformed(evt);
            }
        });

        BTNEmpleados.setBackground(new java.awt.Color(0, 0, 0));
        BTNEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        BTNEmpleados.setText("Empleados");
        BTNEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEmpleadosActionPerformed(evt);
            }
        });

        BTNTipoEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        BTNTipoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        BTNTipoEmpleado.setText("Tipo de Empleado");
        BTNTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTipoEmpleadoActionPerformed(evt);
            }
        });

        BtnVolver.setBackground(new java.awt.Color(0, 0, 0));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        BTNDiasTrabajados.setBackground(new java.awt.Color(0, 0, 0));
        BTNDiasTrabajados.setForeground(new java.awt.Color(255, 255, 255));
        BTNDiasTrabajados.setText("Dias Trabajados");
        BTNDiasTrabajados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDiasTrabajadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNTipoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDepartamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDFeriados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCalendariosCRUD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDiasTrabajados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(BtnVolver)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BTNCalendariosCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNDFeriados, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNDiasTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolverActionPerformed
        // TODO add your handling code here:
        this.hide();
        MenuPrincipal MPrincipal = new MenuPrincipal();
        MPrincipal.show();
    }//GEN-LAST:event_BTNVolverActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        MenuPrincipal MPrincipal = new MenuPrincipal();
        MPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BTNCalendariosCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCalendariosCRUDActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        CalendarioCRUD CalCRUD = new CalendarioCRUD();
        CalCRUD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNCalendariosCRUDActionPerformed

    private void BTNDFeriadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDFeriadosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        DiasFeriadosCRUD DFCRUD = new DiasFeriadosCRUD();
        DFCRUD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNDFeriadosActionPerformed

    private void BTNDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDepartamentosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        DepartamentoCRUD DepCRUD = new DepartamentoCRUD();
        DepCRUD.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BTNDepartamentosActionPerformed

    private void BTNEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEmpleadosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        EmpleadoCRUD EmpCRUD = new EmpleadoCRUD();
        EmpCRUD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNEmpleadosActionPerformed

    private void BTNTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTipoEmpleadoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        TiposEmpleadosCRUD TipEmpCRUD = new TiposEmpleadosCRUD();
        TipEmpCRUD.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BTNTipoEmpleadoActionPerformed

    private void BTNDiasTrabajadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDiasTrabajadosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        DiasTrabajadosCRUD DiasTrabCRUD = new DiasTrabajadosCRUD();
        DiasTrabCRUD.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BTNDiasTrabajadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCalendariosCRUD;
    private javax.swing.JButton BTNDFeriados;
    private javax.swing.JButton BTNDepartamentos;
    private javax.swing.JButton BTNDiasTrabajados;
    private javax.swing.JButton BTNEmpleados;
    private javax.swing.JButton BTNTipoEmpleado;
    private javax.swing.JButton BTNVolver;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
