/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planta;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static planta.PlantaFunciones.consultaTardiasPorPeriodoTiempo;
import static planta.PlantaFunciones.consultaEmpleadosDeBajaPorPeriodo;
import static planta.PlantaFunciones.getNombresDepartamentos;
import static planta.PlantaFunciones.consultaInfoEmpleadosPorDepartamento;



/**
 *
 * @author XPC
 */
public class MenúConsultas extends javax.swing.JFrame {
   
    private String[] opcionesConsulta;
    
    /**
     * Creates new form MenúConsultas
     */
    public MenúConsultas() {
        initComponents();
        
        actualizarCombosBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnConsulta3 = new javax.swing.JButton();
        BtnConsulta1 = new javax.swing.JButton();
        BtnConsulta2 = new javax.swing.JButton();
        BtnConsulta4 = new javax.swing.JButton();
        BtnConsulta5 = new javax.swing.JButton();
        BtnConsulta6 = new javax.swing.JButton();
        BtnConsulta7 = new javax.swing.JButton();
        BtnConsulta8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtIdEmpleado = new javax.swing.JTextField();
        TxtFechaI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtFechaF = new javax.swing.JTextField();
        BtnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxDep = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultas");

        BtnConsulta3.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta3.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta3.setText("<html>Empleados sin marca de salida por periodo de tiempo</html>");
        BtnConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsulta3ActionPerformed(evt);
            }
        });

        BtnConsulta1.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta1.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta1.setText("<html><p>Ausencias por</p><p>periodo de tiempo</p></html>");
        BtnConsulta1.setAutoscrolls(true);
        BtnConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnConsulta1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnConsulta1.setVerifyInputWhenFocusTarget(false);

        BtnConsulta2.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta2.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta2.setText("<html>Tardías por periodo de tiempo</html>");
        BtnConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsulta2ActionPerformed(evt);
            }
        });

        BtnConsulta4.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta4.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta4.setText("<html>Monto ganado por empleado por periodo de tiempo</html>");
        BtnConsulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsulta4ActionPerformed(evt);
            }
        });

        BtnConsulta5.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta5.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta5.setText("<html>Información general de un empleado</html>");
        BtnConsulta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsulta5ActionPerformed(evt);
            }
        });

        BtnConsulta6.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta6.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta6.setText("<html>Información general de empleados por departamento</html>");
        BtnConsulta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsulta6ActionPerformed(evt);
            }
        });

        BtnConsulta7.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta7.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta7.setText("<html>Empleados a cargo de un supervisor</html>");
        BtnConsulta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsulta7ActionPerformed(evt);
            }
        });

        BtnConsulta8.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsulta8.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsulta8.setText("<html>Empleados dados de baja en un periodo de tiempo</html>");
        BtnConsulta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsulta8ActionPerformed(evt);
            }
        });

        TxtArea.setColumns(20);
        TxtArea.setRows(5);
        jScrollPane1.setViewportView(TxtArea);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Id Empleado");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha Inicial");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha Final");

        BtnVolver.setBackground(new java.awt.Color(0, 0, 0));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Departamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(BtnConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(BtnConsulta3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnConsulta4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnConsulta5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnConsulta6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnConsulta7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnConsulta8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(530, 530, 530)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtFechaF, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(TxtFechaI)
                                    .addComponent(TxtIdEmpleado)
                                    .addComponent(comboBoxDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnConsulta3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnConsulta2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnConsulta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnConsulta4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(BtnConsulta5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnConsulta6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(BtnConsulta7)
                            .addComponent(BtnConsulta8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsulta2ActionPerformed
        // TODO add your handling code here:
        if (TxtFechaI.getText().equals("") || TxtFechaF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor colocar un a fecha de inicio y una final", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Pattern pattern = Pattern.compile("^((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$");
        Matcher mat = pattern.matcher(TxtFechaI.getText());
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        mat = pattern.matcher(TxtFechaF.getText());
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(PlantaFunciones.FechaCSentido(TxtFechaI.getText(), TxtFechaF.getText()) == false){
        JOptionPane.showMessageDialog(this, 
                "LA FECHA DE INGRESO DEBE SER ANTERIOR A LA FECHA DE SALIDA", 
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        String salida = consultaTardiasPorPeriodoTiempo(TxtFechaI.getText(), TxtFechaF.getText());
        TxtArea.setText(salida);
        
    }//GEN-LAST:event_BtnConsulta2ActionPerformed

    private void BtnConsulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsulta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsulta4ActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        MenuPrincipal MPrincipal = new MenuPrincipal();
        MPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnConsulta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsulta5ActionPerformed
        // TODO add your handling code here:
        String StrIdEmpleado = TxtIdEmpleado.getText();
        if(PlantaFunciones.isNumeric(StrIdEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "SOLO DEBE INGRESAR NUMEROS EN EL APARTADO DE IDEMPLEADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdEmpleado = Integer.parseInt(StrIdEmpleado);
        if(PlantaFunciones.VerificarIdEmpleadoEmpleados(IdEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN EMPLEADO CON EL IDEMPLEADO INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String Final = PlantaFunciones.Consulta5(IdEmpleado);
        TxtArea.setText(Final);
        
    }//GEN-LAST:event_BtnConsulta5ActionPerformed

    private void BtnConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsulta3ActionPerformed
        // TODO add your handling code here:
        String strFechaI = TxtFechaI.getText();
        Pattern pattern = Pattern.compile("^(19|20)(((([02468][048])|([13579][26]))-02-29)|(\\d{2})-((02-((0[1-9])|1\\d|2[0-8]))|((((0[13456789])|1[012]))-((0[1-9])|((1|2)\\d)|30))|(((0[13578])|(1[02]))-31)))[Tt](([0-1]\\d)|(2[0-3]))(:[0-5]\\d){2}$");
        Matcher mat = pattern.matcher(strFechaI);
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DDTHH:MM:SS", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String NFechaI = strFechaI.substring(0,10) + " "  + strFechaI.substring(11);
        
        String strFechaF = TxtFechaF.getText();
        
        mat = pattern.matcher(strFechaF);
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
              "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DDTHH:MM:SS", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String NFechaF = strFechaF.substring(0,10) + " "  + strFechaF.substring(11);

        String Final = PlantaFunciones.Consulta3(NFechaI, NFechaF);
        TxtArea.setText(Final);
    }//GEN-LAST:event_BtnConsulta3ActionPerformed

    private void BtnConsulta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsulta7ActionPerformed
        // TODO add your handling code here:
        String StrIdEmpleado = TxtIdEmpleado.getText();
        if(PlantaFunciones.isNumeric(StrIdEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "SOLO DEBE INGRESAR NUMEROS EN EL APARTADO DE IDEMPLEADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdEmpleado = Integer.parseInt(StrIdEmpleado);
        if(PlantaFunciones.VerificarIdEmpleadoEmpleados(IdEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN EMPLEADO CON EL IDEMPLEADO INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String Final = PlantaFunciones.Consulta7(IdEmpleado);
        TxtArea.setText(Final + "");
        
    }//GEN-LAST:event_BtnConsulta7ActionPerformed

    private void BtnConsulta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsulta8ActionPerformed
        // TODO add your handling code here:
        if (TxtFechaI.getText().equals("") || TxtFechaF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor colocar un a fecha de inicio y una final", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Pattern pattern = Pattern.compile("^((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$");
        Matcher mat = pattern.matcher(TxtFechaI.getText());
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                    "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        mat = pattern.matcher(TxtFechaF.getText());
        if(!mat.matches()){
        JOptionPane.showMessageDialog(this, 
                "LA FECHA INGRESADA DEBE SER VÁLIDA Y CUMPLIR CON EL FORMATO YYYY-MM-DD", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(PlantaFunciones.FechaCSentido(TxtFechaI.getText(), TxtFechaF.getText()) == false){
        JOptionPane.showMessageDialog(this, 
                "LA FECHA DE INGRESO DEBE SER ANTERIOR A LA FECHA DE SALIDA", 
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        String salida = consultaEmpleadosDeBajaPorPeriodo(TxtFechaI.getText(), TxtFechaF.getText());

        TxtArea.setText(salida); 
    }//GEN-LAST:event_BtnConsulta8ActionPerformed

    private void BtnConsulta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsulta6ActionPerformed
        int idSeleccionado = Integer.parseInt(opcionesConsulta[0].split(",")[comboBoxDep.getSelectedIndex()]);
        String salida = consultaInfoEmpleadosPorDepartamento(idSeleccionado);
        TxtArea.setText(salida);
    }//GEN-LAST:event_BtnConsulta6ActionPerformed

    private void actualizarCombosBox(){
        comboBoxDep.removeAllItems();
        try {
            opcionesConsulta = getNombresDepartamentos();
            String[] opciones = opcionesConsulta[1].split(",");
            for (int i = 0; i < opciones.length; i++) {
                comboBoxDep.addItem(opciones[i]);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenúConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsulta1;
    private javax.swing.JButton BtnConsulta2;
    private javax.swing.JButton BtnConsulta3;
    private javax.swing.JButton BtnConsulta4;
    private javax.swing.JButton BtnConsulta5;
    private javax.swing.JButton BtnConsulta6;
    private javax.swing.JButton BtnConsulta7;
    private javax.swing.JButton BtnConsulta8;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextArea TxtArea;
    private javax.swing.JTextField TxtFechaF;
    private javax.swing.JTextField TxtFechaI;
    private javax.swing.JTextField TxtIdEmpleado;
    private javax.swing.JComboBox<String> comboBoxDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
