/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planta;

import java.util.Date;
import javax.swing.JOptionPane;
import java.util.regex.*;

/**
 *
 * @author prend
 */
public class TiposEmpleadosCRUD extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public TiposEmpleadosCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelConsulta = new javax.swing.JPanel();
        botonConsulta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        panelTextArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        panelEditar = new javax.swing.JPanel();
        botonEditar = new javax.swing.JButton();
        panelEliminar = new javax.swing.JPanel();
        botonEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agregarFDNombreTipo = new javax.swing.JTextField();
        agregarFDIdCalendario = new javax.swing.JTextField();
        agregarFDCostoH = new javax.swing.JTextField();
        agregarFDCostoHE = new javax.swing.JTextField();
        agregarFDCostoHD = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        editarFDIdTipoEmpleado = new javax.swing.JTextField();
        editarFDNombreTipo = new javax.swing.JTextField();
        editarFDIdCalendario = new javax.swing.JTextField();
        editarFDCostoH = new javax.swing.JTextField();
        editarFDCostoHE = new javax.swing.JTextField();
        editarFDCostoHD = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        eliminarFDIdEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BTNConsultarCalendario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        panelConsulta.setBackground(new java.awt.Color(255, 255, 255));

        botonConsulta.setBackground(new java.awt.Color(0, 0, 0));
        botonConsulta.setForeground(new java.awt.Color(255, 255, 255));
        botonConsulta.setText("CONSULTAR");
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultaLayout = new javax.swing.GroupLayout(panelConsulta);
        panelConsulta.setLayout(panelConsultaLayout);
        panelConsultaLayout.setHorizontalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultaLayout.setVerticalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        botonAgregar.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregar.setText("AGREGAR");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTextArea.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout panelTextAreaLayout = new javax.swing.GroupLayout(panelTextArea);
        panelTextArea.setLayout(panelTextAreaLayout);
        panelTextAreaLayout.setHorizontalGroup(
            panelTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelTextAreaLayout.setVerticalGroup(
            panelTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTextAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelEditar.setBackground(new java.awt.Color(255, 255, 255));

        botonEditar.setBackground(new java.awt.Color(0, 0, 0));
        botonEditar.setForeground(new java.awt.Color(255, 255, 255));
        botonEditar.setText("EDITAR");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelEliminar.setBackground(new java.awt.Color(255, 255, 255));

        botonEliminar.setBackground(new java.awt.Color(0, 0, 0));
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("ELIMINAR");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del tipo");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("IdCalendario");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Costo deHora");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Costo de Hora Extra");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Costo de Hora Doble");

        agregarFDNombreTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDNombreTipoActionPerformed(evt);
            }
        });

        agregarFDIdCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDIdCalendarioActionPerformed(evt);
            }
        });

        agregarFDCostoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDCostoHActionPerformed(evt);
            }
        });

        agregarFDCostoHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDCostoHEActionPerformed(evt);
            }
        });

        agregarFDCostoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFDCostoHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarFDNombreTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarFDIdCalendario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarFDCostoH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarFDCostoHE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarFDCostoHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(agregarFDNombreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDIdCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDCostoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDCostoHE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFDCostoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("IdTipoEmpleado");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Nombre del tipo");

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("IdCalendario");

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Costo de Hora");

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("CostoHoraExtra");

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("CostoHoraDoble");

        editarFDIdTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDIdTipoEmpleadoActionPerformed(evt);
            }
        });

        editarFDNombreTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDNombreTipoActionPerformed(evt);
            }
        });

        editarFDIdCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDIdCalendarioActionPerformed(evt);
            }
        });

        editarFDCostoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDCostoHActionPerformed(evt);
            }
        });

        editarFDCostoHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDCostoHEActionPerformed(evt);
            }
        });

        editarFDCostoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFDCostoHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarFDIdTipoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarFDNombreTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarFDIdCalendario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarFDCostoH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarFDCostoHE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarFDCostoHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(editarFDIdTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFDNombreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFDIdCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFDCostoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(editarFDCostoHE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(editarFDCostoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("IdTipoEmpleado");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("<html>Esta funcion solo estará disponible para los Tipos que no hayan sido usados en un empleado<html>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(eliminarFDIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarFDIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(35, 35, 35)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTNConsultarCalendario.setBackground(new java.awt.Color(0, 0, 0));
        BTNConsultarCalendario.setForeground(new java.awt.Color(255, 255, 255));
        BTNConsultarCalendario.setText("<html>Consultar Calendarios<html>");
        BTNConsultarCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConsultarCalendarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(BTNConsultarCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(panelTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BTNConsultarCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        String str = PlantaFunciones.MostrarTiposEmpleados();
        textArea.setText(str);
    }//GEN-LAST:event_botonConsultaActionPerformed

    private void agregarFDNombreTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDNombreTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDNombreTipoActionPerformed

    private void agregarFDIdCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDIdCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDIdCalendarioActionPerformed

    private void agregarFDCostoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDCostoHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDCostoHActionPerformed

    private void agregarFDCostoHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDCostoHEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDCostoHEActionPerformed

    private void agregarFDCostoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFDCostoHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarFDCostoHDActionPerformed

    private void editarFDIdTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDIdTipoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDIdTipoEmpleadoActionPerformed

    private void editarFDNombreTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDNombreTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDNombreTipoActionPerformed

    private void editarFDIdCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDIdCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDIdCalendarioActionPerformed

    private void editarFDCostoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDCostoHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDCostoHActionPerformed

    private void editarFDCostoHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDCostoHEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDCostoHEActionPerformed

    private void editarFDCostoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFDCostoHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFDCostoHDActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        String StrIdTipoEmpleado = editarFDIdTipoEmpleado.getText();
        if(PlantaFunciones.isNumeric(StrIdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdTipoEmpleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdTipoEmpleado = Integer.parseInt(StrIdTipoEmpleado);
        if(PlantaFunciones.VerificarIdTipoEmpleadoTE(IdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN TIPO DE EMPLEADO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(editarFDNombreTipo.getText().length() == 0){
           JOptionPane.showMessageDialog(this, 
                    "Debe ingresar al menos un nombre de tipo", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String NombreTipo = editarFDNombreTipo.getText();
        
        String StrIdCalendario = editarFDIdCalendario.getText();
        if(PlantaFunciones.isNumeric(StrIdCalendario) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdCalendario", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdCalendario = Integer.parseInt(StrIdCalendario);
        if(PlantaFunciones.VerificarIdCalendarios(IdCalendario) == false){
           JOptionPane.showMessageDialog(this, 
                    "NO HAY UN CALENDARIO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        String StrCostoH = editarFDCostoH.getText();
        if(PlantaFunciones.isNumeric(StrCostoH) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de Costo de Horas", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int CostoH = Integer.parseInt(StrCostoH);
        
        String StrCostoHE = editarFDCostoHE.getText();
        if(PlantaFunciones.isNumeric(StrCostoHE) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de Costo de Horas Extra", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int CostoHE = Integer.parseInt(StrCostoHE);
        
        String StrCostoHD = editarFDCostoHD.getText();
        if(PlantaFunciones.isNumeric(StrCostoHD) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de Costo de Horas Doble", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int CostoHD = Integer.parseInt(StrCostoHD);
        
        boolean Bandera = PlantaFunciones.EditarTipoEmpleado(IdTipoEmpleado, IdCalendario, CostoH, CostoHE, CostoHD, NombreTipo);
        if(Bandera == true){
            JOptionPane.showMessageDialog(this, 
                    "EL PROCESO SE HA REALIZADO DE MANERA EXITOSA", 
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        JOptionPane.showMessageDialog(this, 
                    "NO SE HA REALIZADO EL PROCESO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
        
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        String NombreTipo = agregarFDNombreTipo.getText();
        String StrIdCalendario = agregarFDIdCalendario.getText();
        if(PlantaFunciones.isNumeric(StrIdCalendario) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdCalendario", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdCalendario = Integer.parseInt(StrIdCalendario);
        if(PlantaFunciones.VerificarIdCalendarios(IdCalendario) == false){
           JOptionPane.showMessageDialog(this, 
                    "NO HAY UN CALENDARIO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String StrCostoH = agregarFDCostoH.getText();
        if(PlantaFunciones.isNumeric(StrCostoH) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de Costo de Horas", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int CostoH = Integer.parseInt(StrCostoH);
        
        String StrCostoHE = agregarFDCostoHE.getText();
        if(PlantaFunciones.isNumeric(StrCostoHE) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de Costo de Horas Extra", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int CostoHE = Integer.parseInt(StrCostoHE);
        
        String StrCostoHD = agregarFDCostoHD.getText();
        if(PlantaFunciones.isNumeric(StrCostoHD) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de Costo de Horas Doble", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int CostoHD = Integer.parseInt(StrCostoHD);
        
        int IdTipo = PlantaFunciones.InsertarNombreTipo(NombreTipo);
        boolean Bandera = PlantaFunciones.InsertarTipoEmpleado(IdTipo, IdCalendario, CostoH, CostoHE, CostoHD);
        if(Bandera == true){
            JOptionPane.showMessageDialog(this, 
                    "EL PROCESO SE HA REALIZADO DE MANERA EXITOSA", 
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        JOptionPane.showMessageDialog(this, 
                    "NO SE HA REALIZADO EL PROCESO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
        
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        String StrIdTipoEmpleado = eliminarFDIdEmpleado.getText();
        if(PlantaFunciones.isNumeric(StrIdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "Solo debe ingresar numeros en el apartado de IdTipoEmpleado", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int IdTipoEmpleado = Integer.parseInt(StrIdTipoEmpleado);
        if(PlantaFunciones.VerificarIdTipoEmpleadoTE(IdTipoEmpleado) == false){
            JOptionPane.showMessageDialog(this, 
                    "NO EXISTE UN TIPO DE EMPLEADO CON EL ID INGRESADO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int CantidadEPTE = PlantaFunciones.ObtenerEPorTE(IdTipoEmpleado);
        System.out.println("Aqui: " + CantidadEPTE);
        if(CantidadEPTE > 0){
            JOptionPane.showMessageDialog(this, 
                    "NO PUEDE ELIMINAR UN TIPO DE EMPLEADO QUE YA CUENTA CON EMPLEADOS", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean Bandera = PlantaFunciones.EliminarTipoEmpleado(IdTipoEmpleado);
        if(Bandera == true){
            JOptionPane.showMessageDialog(this, 
                    "EL PROCESO SE HA REALIZADO DE MANERA EXITOSA", 
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        JOptionPane.showMessageDialog(this, 
                    "NO SE HA REALIZADO EL PROCESO", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void BTNConsultarCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConsultarCalendarioActionPerformed
        // TODO add your handling code here:
        String str = PlantaFunciones.MostrarInfCalendarios();
        textArea.setText(str);
        
    }//GEN-LAST:event_BTNConsultarCalendarioActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiposEmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiposEmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiposEmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiposEmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiposEmpleadosCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNConsultarCalendario;
    private javax.swing.JTextField agregarFDCostoH;
    private javax.swing.JTextField agregarFDCostoHD;
    private javax.swing.JTextField agregarFDCostoHE;
    private javax.swing.JTextField agregarFDIdCalendario;
    private javax.swing.JTextField agregarFDNombreTipo;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField editarFDCostoH;
    private javax.swing.JTextField editarFDCostoHD;
    private javax.swing.JTextField editarFDCostoHE;
    private javax.swing.JTextField editarFDIdCalendario;
    private javax.swing.JTextField editarFDIdTipoEmpleado;
    private javax.swing.JTextField editarFDNombreTipo;
    private javax.swing.JTextField eliminarFDIdEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTextArea;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
